### ISSUE TITLE
Can steps outlined in chromVAR be followed by specific commands from ATACCoGAPS

### ISSUE THREAD

**Issue by sylestiel** [FertigLab/ATACCoGAPS#32]
Hi,

 If I'm using chromVAR vignette can I use commands like heatmapGeneAccessibility from ATACCoGAPS simply by reading in the library or are there other mandatory steps from the ATACCoGAPS vignette that must  be run first.

Thanks!

**Comment by rossinerbe** [comment]
You first need to run the geneAccessibility function for the set of genes you want to include in the heatmap, but that does not require anything specific to the rest of the CoGAPS pipeline. 

Just to clarify that this does what you want: this will plot the peaks covering each gene across all samples/cells in the data so you can see if accessibility for those genes differs across groups of samples/cells.

**Comment by sylestiel** [comment]
Thank you!

**Comment by sylestiel** [comment]
> genePeaks <- geneAccessibility(geneList = geneList, peakGranges =example_counts, atacData = counts_filtered, genome = Mus.musculus)
'select()' returned 1:1 mapping between keys and columns
'select()' returned 1:1 mapping between keys and columns
Error in binaryATAC[x, ] : incorrect number of dimensions


How may I address this error

**Comment by rossinerbe** [comment]
It's hard to say for sure without looking at your input data. Is your counts_filtered object a matrix?

**Comment by sylestiel** [comment]
It is LargeRangedSummarizedExperiment
![counts_filtered](https://user-images.githubusercontent.com/64283689/95683531-84333f00-0bb1-11eb-9c7d-de2e9d57b52a.png)

**Comment by rossinerbe** [comment]
You need to find where the counts are in that object, pull that out, and use as.matrix to make it a matrix.

**Comment by sylestiel** [comment]
Looking at the chromVAR vignette can you suggest how and where I could incorporate geneAccessibility() and the heatmap for visualization. 
I can't seem to get it working
https://greenleaflab.github.io/chromVAR/articles/Introduction.html

**Comment by rossinerbe** [comment]
If your counts_filtered object is formatted like the example_counts object, this will work

`as.matrix(counts_filtered@assays$data[[1]])`

**Comment by sylestiel** [comment]
> example_counts <- as.matrix(example_counts@assays$rowRanges[[1]])
Error in example_counts@assays$rowRanges : 
  $ operator not defined for this S4 class
> fragment_counts <- as.matrix(counts_filtered@assays$rowRanges[[1]])
Error in counts_filtered@assays$rowRanges : 
  $ operator not defined for this S4 class
> genePeaks <- geneAccessibility(geneList = geneList, peakGranges = example_counts, atacData = fragment_counts, genome = Mus.musculus)
'select()' returned 1:1 mapping between keys and columns
'select()' returned 1:1 mapping between keys and columns
Error in binaryATAC[x, ] : incorrect number of dimensions
> heatmapGeneAccessibility(genePeaks, celltypes, colColors = Null, order =TRUE, seed =42) + theme(text = element_text(size=20, face = "bold"))
Error in heatmapGeneAccessibility(genePeaks, celltypes, colColors = Null,  : 
  object 'genePeaks' not found
